# Generated by Django 3.0.3 on 2020-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('location', models.CharField(max_length=100, verbose_name='Расположение офиса')),
                ('organization', models.CharField(max_length=150, verbose_name='Название компании')),
                ('salary', models.CharField(default='Договорная', max_length=100, verbose_name='ЗП')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
